# Generated by Django 4.0.6 on 2023-02-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.CharField(blank=True, default=None, max_length=140, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ManyToManyField(related_name='user_badges', to='final_main_app.appuser')),
            ],
        ),
    ]
