# Generated by Django 4.0.6 on 2022-10-21 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('final_main_app', '0002_appuser_author_category_alter_image_id_story_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appuser',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
