# Generated by Django 3.0 on 2022-07-14 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('final_main_app', '0005_auto_20220714_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='final_main_app.AppUser'),
        ),
        migrations.AlterField(
            model_name='userfriends',
            name='friend_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userfriends_friend_id', to='final_main_app.AppUser'),
        ),
        migrations.AlterField(
            model_name='userfriends',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userfriends_user_id', to='final_main_app.AppUser'),
        ),
    ]
