# Generated by Django 4.0.6 on 2022-10-28 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_main_app', '0005_remove_answer_accepted_answer_down_vote_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='down_vote',
            new_name='down_votes',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='upvote',
            new_name='upvotes',
        ),
    ]
