# Generated by Django 4.0.6 on 2022-07-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_main_app', '0007_alter_appuser_id_alter_image_id_alter_userfriends_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='appuser_friends', to='final_main_app.appuser'),
        ),
        migrations.DeleteModel(
            name='UserFriends',
        ),
    ]
