# Generated by Django 4.0.6 on 2022-08-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_main_app', '0008_appuser_friends_delete_userfriends'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
