# Generated by Django 4.0.6 on 2023-01-09 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('final_main_app', '0009_group_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_appuser', to='final_main_app.category'),
        ),
    ]
