# Generated by Django 4.0.6 on 2023-01-09 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('final_main_app', '0010_appuser_interest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='interest',
        ),
        migrations.AddField(
            model_name='appuser',
            name='interest',
            field=models.ManyToManyField(related_name='categories_appusers', to='final_main_app.category'),
        ),
        migrations.AlterField(
            model_name='story',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_stories', to='final_main_app.category'),
        ),
    ]
