# Generated by Django 4.0.6 on 2023-01-09 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_main_app', '0011_remove_appuser_interest_appuser_interest_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='interest',
            new_name='interests',
        ),
    ]
