# Generated by Django 4.0.6 on 2022-10-18 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_main_app', '0011_alter_chat_name_alter_group_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='user',
            new_name='users',
        ),
    ]
