# Generated by Django 4.0.6 on 2022-10-19 08:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('final_main_app', '0012_rename_user_group_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='description',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='name',
        ),
        migrations.AddField(
            model_name='chat',
            name='room_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(related_name='groups', to='final_main_app.appuser'),
        ),
    ]
