# Generated by Django 4.0.6 on 2022-10-19 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('final_main_app', '0014_story_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='stories',
        ),
        migrations.AddField(
            model_name='story',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='final_main_app.category'),
        ),
    ]
