# Generated by Django 4.0.6 on 2023-01-24 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('final_main_app', '0015_alter_answer_question_alter_answer_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('peer', 'peer'), ('counselor', 'counselor'), ('coach', 'coach'), ('support_buddy', 'support_buddy')], max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='replies',
            field=models.ManyToManyField(blank=True, related_name='answer_replies', to='final_main_app.answer'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='role',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='final_main_app.role'),
        ),
    ]
